import { describe, expect, it } from "vitest";

import type { Company, Customer, Invoice } from "./types";
import {
  formatSchemaIssues,
  validateNFeXmlSchema,
} from "./nfe-schema-validate";
import { buildInvoiceXml } from "./xml-export";
import { getSefazStatusInfo, formatSefazRejection } from "./sefaz-cstat";

const company: Company = {
  id: 1,
  name: "Comercial LTDA",
  tradeName: "Comercial",
  document: "04252011000110",
  stateRegistration: "123456789012",
  email: null,
  phone: null,
  zip: "01001000",
  street: "Praca da Se",
  number: "100",
  complement: null,
  district: "Se",
  city: "Sao Paulo",
  state: "SP",
  taxRegime: "simples",
  nfeSeries: 1,
  nextNfeNumber: 1,
  sefazEnvironment: "homologation",
  municipalRegistration: null,
  rpsSeries: "A",
  nextRpsNumber: 1,
  createdAt: 0,
  updatedAt: 0,
};

const customer: Customer = {
  id: 1,
  companyId: 1,
  name: "Cliente",
  document: "52998224725",
  stateRegistration: null,
  email: "a@b.com",
  phone: null,
  zip: "01310100",
  street: "Av Paulista",
  number: "1000",
  complement: null,
  district: "Bela Vista",
  city: "Sao Paulo",
  state: "SP",
  notes: null,
  createdAt: 0,
  updatedAt: 0,
};

const invoice: Invoice = {
  id: 1,
  companyId: 1,
  customerId: 1,
  number: 1,
  series: 1,
  nature: "Venda",
  cfop: "5102",
  status: "draft",
  subtotalCents: 10000,
  taxCents: 600,
  stCents: 0,
  totalCents: 10600,
  xmlContent: null,
  rejectionReason: null,
  sefazProtocol: null,
  accessKey: null,
  cancelProtocol: null,
  cancelJustification: null,
  canceledAt: null,
  issuedAt: null,
  items: [
    {
      id: 1,
      invoiceId: 1,
      productId: 1,
      description: "Item",
      ncm: "73181500",
      quantity: 1,
      unitPriceCents: 10000,
      totalCents: 10000,
      createdAt: 0,
    },
  ],
  createdAt: 0,
  updatedAt: 0,
};

describe("validateNFeXmlSchema", () => {
  it("accepts XML generated by buildInvoiceXml (homologação)", () => {
    const xml = buildInvoiceXml({
      company,
      customer,
      invoice,
      cNF: "12345678",
    });
    const result = validateNFeXmlSchema(xml);
    expect(result.ok).toBe(true);
  });

  it("rejects empty xml", () => {
    const result = validateNFeXmlSchema("");
    expect(result.ok).toBe(false);
    if (!result.ok) expect(result.issues[0].code).toBe("XSD-EMPTY");
  });

  it("flags missing NCM format and default address in production", () => {
    const bad = `<NFe><infNFe Id="NFe${"1".repeat(44)}" versao="4.00">
      <ide><cUF>35</cUF><cNF>12345678</cNF><natOp>V</natOp><mod>55</mod>
      <serie>1</serie><nNF>1</nNF><dhEmi>2026-01-01T10:00:00-03:00</dhEmi>
      <tpNF>1</tpNF><idDest>1</idDest><cMunFG>3550308</cMunFG><tpImp>1</tpImp>
      <tpEmis>1</tpEmis><cDV>1</cDV><tpAmb>1</tpAmb><finNFe>1</finNFe>
      <indFinal>1</indFinal><indPres>1</indPres><procEmi>0</procEmi><verProc>1</verProc></ide>
      <emit><CNPJ>04252011000110</CNPJ><xNome>E</xNome>
      <enderEmit><xLgr>RUA NAO INFORMADA</xLgr><nro>1</nro><xBairro>C</xBairro>
      <cMun>3550308</cMun><xMun>SP</xMun><UF>SP</UF><CEP>01001000</CEP></enderEmit>
      <IE>ISENTO</IE><CRT>1</CRT></emit>
      <dest><CPF>52998224725</CPF><xNome>Cliente</xNome>
      <enderDest><xLgr>R</xLgr><nro>1</nro><xBairro>C</xBairro>
      <cMun>3550308</cMun><xMun>SP</xMun><UF>SP</UF><CEP>01001000</CEP></enderDest>
      <indIEDest>9</indIEDest></dest>
      <det nItem="1"><prod><cProd>1</cProd><xProd>X</xProd><NCM>123</NCM><CFOP>5102</CFOP>
      <uCom>UN</uCom><qCom>1</qCom><vUnCom>1.00</vUnCom><vProd>1.00</vProd><indTot>1</indTot></prod>
      <imposto><ICMS><ICMSSN102><orig>0</orig><CSOSN>102</CSOSN></ICMSSN102></ICMS></imposto></det>
      <total><ICMSTot><vBC>0</vBC><vICMS>0</vICMS><vProd>1.00</vProd><vPIS>0</vPIS><vCOFINS>0</vCOFINS><vNF>1.00</vNF></ICMSTot></total>
      <transp><modFrete>9</modFrete></transp>
      <pag><detPag><tPag>99</tPag><vPag>1.00</vPag></detPag></pag>
    </infNFe></NFe>`;

    const result = validateNFeXmlSchema(bad);
    expect(result.ok).toBe(false);
    if (!result.ok) {
      const codes = result.issues.map((i) => i.code);
      expect(codes).toContain("XSD-DET-NCM");
      expect(codes).toContain("XSD-ADDR-DEFAULT");
      expect(formatSchemaIssues(result.issues)).toMatch(/Validação layout 4\.00/);
    }
  });
});

describe("sefaz cStat messages", () => {
  it("maps known codes to actionable text", () => {
    const info = getSefazStatusInfo("215");
    expect(info.kind).toBe("reject");
    expect(info.howToFix).toMatch(/XSD|XML/i);
    const msg = formatSefazRejection("215", "Falha no schema XML");
    expect(msg).toContain("[cStat 215]");
    expect(msg).toContain("O que fazer:");
  });

  it("handles unknown codes", () => {
    const msg = formatSefazRejection("999", "Motivo custom");
    expect(msg).toContain("999");
    expect(msg).toContain("Motivo custom");
  });
});
