/** Códigos de serviço da NFS-e da Prefeitura de São Paulo (Anexo 1 IN SF/SUREM 08/2011). */
export type NfseServiceCode = {
  code: string;
  label: string;
};

export const NFSE_SERVICE_CODES: NfseServiceCode[] = [
  { code: "01015", label: "Obras hidráulicas, sondagem, perfuração de poços, escavação, drenagem e irrigação" },
  { code: "01023", label: "Obras de construção civil, elétrica e serviços auxiliares" },
  { code: "01024", label: "montagem de produtos, peças e equipamentos que se agreguem ao imóvel (exceto o fornecimento de mercadorias" },
  { code: "01031", label: "Demolição" },
  { code: "01032", label: "Demolição. Exclusivo para o ISS – “Habite-se”" },
  { code: "01058", label: "Reparação, conservação e reforma de edifícios, estradas, pontes e congêneres" },
  { code: "01059", label: "produzidas pelo prestador dos serviços, fora do local da prestação dos Reparação, conservação e reforma de" },
  { code: "01090", label: "produzidas pelo prestador dos serviços, fora do local da prestação dos Escoramento, contenção de encostas e" },
  { code: "01104", label: "Carpintaria e serralheria" },
  { code: "01105", label: "Carpintaria e serralheria (profissional autônomo)" },
  { code: "01113", label: "7.02; 7,04; Prestação de serviço do grupo Construção Civil, prestado por 01112" },
  { code: "01114", label: "fora do local da prestação dos serviços, que fica sujeito ao ICMS), no caso de serviços prestados na" },
  { code: "01115", label: "imóvel (exceto o fornecimento de mercadorias produzidas pelo prestador de serviços fora do local da prestação" },
  { code: "01116", label: "sede da abertura da Copa do Mundo FIFA 2014. Reparação, conservação e reforma de edifícios, estradas, pontes" },
  { code: "01117", label: "construção do Estádio sede da abertura da Copa do Mundo FIFA 2014 Escoramento, contenção de encostas e" },
  { code: "01118", label: "Copa do Mundo FIFA 2014. Carpintaria e serralheria, no caso de serviços prestados na construção do Estádio" },
  { code: "01119", label: "Acompanhamento e fiscalização da execução de obras de engenharia, arquitetura e urbanismo, no caso de" },
  { code: "01121", label: "do Estádio sede da abertura da Copa do Mundo FIFA 2014. Aerofotogrametria (inclusive interpretação)" },
  { code: "01139", label: "geológicos, geofísicos e congêneres, no caso de serviços prestados na construção do Estádio sede da abertura" },
  { code: "01210", label: "Paisagismo" },
  { code: "01228", label: "Colocação e instalação de tapetes, carpetes, assoalhos, cortinas, revestimentos de parede, vidros" },
  { code: "01236", label: "congêneres, com material fornecido pelo tomador do serviço. Recuperação, raspagem, polimento e lustração de" },
  { code: "01244", label: "Calafetação" },
  { code: "01325", label: "Varrição, coleta, remoção, incineração, tratamento, reciclagem, separação e destinação final de lixo" },
  { code: "01384", label: "quaisquer. Limpeza, manutenção e conservação de vias e logradouros públicos" },
  { code: "01406", label: "parques, jardins e congêneres. Limpeza, manutenção e conservação de imóveis, chaminés, piscinas e" },
  { code: "01422", label: "congêneres, inclusive fossas. Limpeza, manutenção e conservação de imóveis, chaminés, piscinas e" },
  { code: "01430", label: "congêneres, inclusive fossas, prestados por profissional autônomo. Decoração" },
  { code: "01449", label: "Jardinagem, inclusive corte e poda de árvores" },
  { code: "01465", label: "Dedetização, desinfecção, desinsetização, imunização, higienização" },
  { code: "01473", label: "desratização, pulverização e congêneres. Limpeza e dragagem de rios, portos, canais, baías, lagos, lagoas" },
  { code: "01481", label: "represas, açudes e congêneres. pedágio dos usuários, envolvendo execução de serviços de conservação" },
  { code: "01503", label: "capacidade e segurança de trânsito, operação, monitoração, assistência aos usuários e outros serviços" },
  { code: "01504", label: "7.11" },
  { code: "01520", label: "Engenharia, agronomia, arquitetura, urbanismo e congêneres" },
  { code: "01538", label: "Engenheiro, agrônomo, arquiteto, urbanista e congêneres (profissional" },
  { code: "01546", label: "autônomo). Engenharia, agronomia, arquitetura, urbanismo e congêneres (regime" },
  { code: "01589", label: "especial - sociedade). Agrimensura, geologia e congêneres" },
  { code: "01600", label: "Agrimensor, geólogo e congêneres (profissional autônomo)" },
  { code: "01627", label: "Agrimensura, geologia e congêneres (regime especial - sociedade)" },
  { code: "01694", label: "Elaboração de planos diretores, estudos de viabilidade, estudos organizacionais e outros, relacionados com" },
  { code: "01724", label: "engenharia; elaboração de anteprojetos, projetos básicos e projetos executivos para trabalhos de engenharia" },
  { code: "01740", label: "físicos, químicos e biológicos. Florestamento, reflorestamento, semeadura, adubação e congêneres" },
  { code: "01805", label: "Florestamento, reflorestamento, semeadura, adubação, reparação de solo, plantio, silagem, colheita, corte e" },
  { code: "01821", label: "arquitetura e urbanismo. Aerofotogrametria (inclusive interpretação), cartografia, mapeamento, levantamentos" },
  { code: "01848", label: "geológicos, geofísicos e congêneres. Cartógrafo, geógrafo, profissional de geodésia e geofísico (profissional" },
  { code: "01856", label: "autônomo). Topógrafo (profissional autônomo)" },
  { code: "01864", label: "Pesquisa, perfuração, cimentação, mergulho, perfilagem, concretação, testemunhagem, pescaria, estimulação e" },
  { code: "01872", label: "com a exploração e explotação de petróleo, gás natural e de outros recursos minerais. Nucleação e" },
  { code: "01880", label: "Assistência técnica" },
  { code: "01899", label: "Planejamento, coordenação, programação ou organização técnica" },
  { code: "01902", label: "financeira ou administrativa. Perícias, laudos, exames técnicos e análises técnicas, inclusive" },
  { code: "01903", label: "institutos psicotécnicos. Inspeção ambiental veicular" },
  { code: "02020", label: "Perícias, laudos, exames técnicos e análises técnicas, sem exigência" },
  { code: "02038", label: "de formação em nível superior (profissional autônomo). Análise de Organização e Métodos" },
  { code: "02054", label: "Desenho industrial" },
  { code: "02062", label: "Desenhista industrial (profissional autônomo)" },
  { code: "02097", label: "Serviços de assistência social" },
  { code: "02100", label: "Assistente social (profissional autônomo)" },
  { code: "02119", label: "Serviços de avaliação de bens e serviços de qualquer natureza" },
  { code: "02135", label: "Avaliador (profissional autônomo)" },
  { code: "02143", label: "Serviços de biologia, biotecnologia e química" },
  { code: "02151", label: "Serviço 02151" },
  { code: "02186", label: "telecomunicações e congêneres. Serviços de desenhos técnicos" },
  { code: "02194", label: "Desenhista técnico (profissional autônomo)" },
  { code: "02216", label: "Serviços de meteorologia" },
  { code: "02224", label: "Serviços de museologia" },
  { code: "02232", label: "7.03" },
  { code: "02321", label: "Técnico-Científico, prestado por profissional autônomo" },
  { code: "02330", label: "Metropolitano de São Paulo – METRÔ. Transporte por ônibus (concessionária e permissionárias)" },
  { code: "02348", label: "ferroviário e aquaviário de passageiros (exceto transporte coletivo de" },
  { code: "02364", label: "Transporte por táxi, explorado por pessoa jurídica" },
  { code: "02402", label: "2350 16.02 Transporte por táxi (profissional autônomo)" },
  { code: "02410", label: "Transporte de escolares (profissional autônomo)" },
  { code: "02429", label: "Transporte de pessoas, por qualquer meio, dentro do território do" },
  { code: "02445", label: "município. Transporte de bens ou valores, dentro do território do Município" },
  { code: "02453", label: "(inclusive auto-socorro e transporte de veículos)" },
  { code: "02461", label: "agências franqueadas. documentos, objetos, bens ou valores, realizados inclusive por courrier" },
  { code: "02488", label: "e congêneres. Prestação de serviço não referenciado em outro código do grupo ; 26.01" },
  { code: "02496", label: "Transporte Municipal, prestado por profissional autônomo. Prestação de serviço não referenciado em outro" },
  { code: "02500", label: "de desenhos, textos e demais materiais publicitários. Inserção de textos, desenhos e outros materiais de" },
  { code: "02526", label: "2501 23.01 Serviços de programação visual, comunicação visual e congêneres" },
  { code: "02534", label: "(profissional autônomo)" },
  { code: "02542", label: "públicas. Prestação de serviço não referenciado em outro código do grupo Mercadologia e Comunicação, prestado" },
  { code: "02658", label: "Análise e desenvolvimento de sistemas" },
  { code: "02666", label: "Programação" },
  { code: "02682", label: "Processamento de dados e outros serviços de informática" },
  { code: "02683", label: "Técnico-Administrativo e congêneres" },
  { code: "02690", label: "Elaboração de programas de computadores (software)" },
  { code: "02691", label: "Elaboração de software, inclusive jogos eletrônicos; licenciamento ou cessão de uso" },
  { code: "02798", label: "Licenciamento ou cessão de direito de uso de programas de computação" },
  { code: "02836", label: "computação, inclusive distribuição" },
  { code: "02879", label: "Assessoria e consultoria em informática" },
  { code: "02917", label: "Suporte técnico em informática, inclusive instalação e configuração" },
  { code: "02918", label: "Manutenção de programas de computação e bancos de dados" },
  { code: "02933", label: "Planejamento, confecção, manutenção e atualização de páginas eletrônicas" },
  { code: "03085", label: "eletrônicas" },
  { code: "03093", label: "Análise, exame, pesquisa, coleta, compilação e fornecimento de dados" },
  { code: "03115", label: "e informações de qualquer natureza, inclusive cadastro e similares. Assessoria ou consultoria de qualquer" },
  { code: "03123", label: "itens desta lista. Tradução e interpretação" },
  { code: "03131", label: "Tradutor e intérprete (profissional autônomo)" },
  { code: "03158", label: "Datilografia, digitação, estenografia, expediente, secretaria em geral, redação, edição, revisão, apoio e" },
  { code: "03159", label: "congêneres. Resposta audível (centrais de “call center” e telemarketing)" },
  { code: "03166", label: "Datilógrafo, digitador, estenógrafo, expediente, secretaria em geral, redator, editor, revisor, apoio e" },
  { code: "03167", label: "congêneres (profissional autônomo). Resposta audível (centrais de “call center” e telemarketing) -" },
  { code: "03174", label: "profissional autônomo. Datilógrafo, não estabelecido (profissional autônomo)" },
  { code: "03204", label: "Administração em geral, inclusive de bens e negócios de terceiros" },
  { code: "03205", label: "exceto imóveis. Fornecimento e administração de vales-refeição, vales-alimentação, vales-transporte e" },
  { code: "03212", label: "cartões eletrônicos ou magnéticos, ou outros oriundos de tecnologia adequada. Fornecimento e administração de" },
  { code: "03220", label: "realizada via plataforma digital" },
  { code: "03239", label: "Advogado (profissional autônomo)" },
  { code: "03379", label: "Advocacia (regime especial - sociedade)" },
  { code: "03387", label: "Arbitragem de qualquer espécie, inclusive jurídica" },
  { code: "03395", label: "Auditoria" },
  { code: "03425", label: "Auditor (profissional autônomo)" },
  { code: "03433", label: "Auditoria (regime especial - sociedade)" },
  { code: "03450", label: "Atuária e cálculos técnicos de qualquer natureza" },
  { code: "03468", label: "Atuário e calculista técnico (profissional autônomo)" },
  { code: "03476", label: "Contabilidade, inclusive serviços técnicos e auxiliares" },
  { code: "03611", label: "Contador e congêneres, com nível superior (profissional autônomo)" },
  { code: "03620", label: "Contador, técnico em contabilidade, guarda-livros e congêneres" },
  { code: "03638", label: "(regime especial - sociedade). Técnico em contabilidade, guarda-livros e congêneres (profissional" },
  { code: "03654", label: "autônomo). Consultoria e assessoria econômica ou financeira" },
  { code: "03670", label: "Economista (profissional autônomo)" },
  { code: "03700", label: "Economistas (regime especial - sociedade)" },
  { code: "03719", label: "Estatística" },
  { code: "03743", label: "Assessoria, análise, avaliação, atendimento, consulta, cadastro, seleção, gerenciamento de informações" },
  { code: "03751", label: "receber ou a pagar e em geral, relacionados a operações de faturização (\"factoring\"). Apresentação de" },
  { code: "03877", label: "autenticação de documentos, reconhecimento de firmas e prestação de" },
  { code: "03878", label: "informações por qualquer forma ou meio quando o interessado dispensar a certidão correspondente. Autenticação" },
  { code: "03956", label: "dispensar a certidão correspondente, prestados por notários, oficiais de registro ou seus prepostos. Serviços" },
  { code: "03980", label: "17.01" },
  { code: "04030", label: "17.22" },
  { code: "04073", label: "Médico e biomédico (profissional autônomo)" },
  { code: "04111", label: "Medicina e biomedicina (regime especial - sociedade)" },
  { code: "04139", label: "Análises clínicas" },
  { code: "04140", label: "Radioterapia, quimioterapia, ultra-sonografia, ressonância magnética" },
  { code: "04146", label: "radiologia, tomografia e congêneres. Análises clínicas, patologia, eletricidade médica, radioterapia" },
  { code: "04154", label: "tomografia e congêneres (profissional autônomo). Análises clínicas, patologia, eletricidade médica" },
  { code: "04170", label: "tomografia e congêneres (regime especial - sociedade). Laboratórios" },
  { code: "04189", label: "Hospitais" },
  { code: "04197", label: "Clínicas e casas de saúde" },
  { code: "04219", label: "Ambulatórios e prontos socorros" },
  { code: "04235", label: "Sanatórios, manicômios e congêneres" },
  { code: "04251", label: "Instrumentação cirúrgica" },
  { code: "04260", label: "Acupuntura" },
  { code: "04278", label: "Acupunturista (profissional autônomo)" },
  { code: "04316", label: "Enfermagem, inclusive serviços auxiliares" },
  { code: "04340", label: "Enfermeiro (profissional autônomo)" },
  { code: "04359", label: "Enfermagem, inclusive serviços auxiliares (regime especial -" },
  { code: "04375", label: "sociedade). Técnico em enfermagem, inclusive serviços auxiliares (profissional" },
  { code: "04383", label: "autônomo). Serviços farmacêuticos" },
  { code: "04391", label: "Fisioterapia" },
  { code: "04421", label: "Fisioterapeuta (profissional autônomo)" },
  { code: "04430", label: "Fisioterapia (regime especial - sociedade)" },
  { code: "04472", label: "Fonoaudiologia" },
  { code: "04499", label: "Fonoaudiólogo (profissional autônomo)" },
  { code: "04502", label: "Fonoaudiologia (regime especial - sociedade)" },
  { code: "04510", label: "Terapia ocupacional" },
  { code: "04545", label: "Terapeuta ocupacional (profissional autônomo)" },
  { code: "04553", label: "Terapia ocupacional (regime especial - sociedade)" },
  { code: "04588", label: "Terapias de qualquer espécie destinadas ao tratamento físico, orgânico" },
  { code: "04596", label: "e mental, inclusive massoterapia, naturologia e naturopatia. Terapeuta de qualquer espécie destinado ao" },
  { code: "04626", label: "(profissional autônomo). Nutrição" },
  { code: "04634", label: "Obstetrícia" },
  { code: "04650", label: "Obstetra (profissional autônomo)" },
  { code: "04677", label: "Obstetrícia (regime especial - sociedade)" },
  { code: "04693", label: "Odontologia" },
  { code: "04723", label: "Dentista (profissional autônomo)" },
  { code: "04731", label: "Odontologia (regime especial - sociedade)" },
  { code: "04774", label: "Ortóptica" },
  { code: "04871", label: "Ortóptico (profissional autônomo)" },
  { code: "04901", label: "Ortóptica (regime especial - sociedade)" },
  { code: "05037", label: "Próteses sob encomenda" },
  { code: "05053", label: "Protético (profissional autônomo)" },
  { code: "05096", label: "Próteses sob encomenda (regime especial - sociedade)" },
  { code: "05100", label: "Psicanálise" },
  { code: "05118", label: "Psicologia" },
  { code: "05134", label: "Psicólogo, clínico ou não (profissional autônomo)" },
  { code: "05142", label: "Psicologia, clínica ou não, exceto psicanálise (regime especial -" },
  { code: "05150", label: "sociedade). Casas de repouso e congêneres" },
  { code: "05177", label: "Creches" },
  { code: "05185", label: "Asilos" },
  { code: "05193", label: "Inseminação artificial, fertilização \"in vitro\" e congêneres" },
  { code: "05223", label: "Bancos de sangue, leite, pele, olhos, óvulos, sêmen e congêneres" },
  { code: "05231", label: "Coleta de sangue, leite, tecidos, sêmen, órgãos e materiais biológicos" },
  { code: "05266", label: "de qualquer espécie. Unidade de atendimento, assistência ou tratamento móvel e" },
  { code: "05274", label: "congêneres. Planos de medicina de grupo ou individual e convênios para prestação" },
  { code: "05312", label: "de assistência médica, hospitalar, odontológica e congêneres. Outros planos de saúde que se cumpram através" },
  { code: "05380", label: "operador do plano mediante indicação do beneficiário. Medicina veterinária e zootecnia" },
  { code: "05398", label: "Médico veterinário e zootécnico (profissional autônomo)" },
  { code: "05410", label: "Medicina veterinária e zootecnia (regime especial - sociedade)" },
  { code: "05428", label: "Hospitais, clínicas, ambulatórios, prontos-socorros e congêneres, na" },
  { code: "05436", label: "área veterinária. Laboratórios de análise na área veterinária" },
  { code: "05460", label: "Inseminação artificial, fertilização \"in vitro\" e congêneres, na área" },
  { code: "05479", label: "veterinária. Bancos de sangue e de órgãos e congêneres, na área veterinária" },
  { code: "05495", label: "Coleta de sangue, leite, tecidos, sêmen, órgãos e materiais biológicos" },
  { code: "05517", label: "de qualquer espécie, na área veterinária. Unidade de atendimento, assistência ou tratamento móvel e" },
  { code: "05533", label: "congêneres, na área veterinária. Planos de atendimento e assistência médico-veterinária" },
  { code: "05539", label: "Farmacêutico (profissional autônomo)" },
  { code: "05540", label: "Nutricionista (profissional autônomo)" },
  { code: "05543", label: "4.03" },
  { code: "05576", label: "Saúde, prestado por profissional autônomo" },
  { code: "05584", label: "Casas de recuperação" },
  { code: "05657", label: "Ginástica, dança, esportes, natação, artes marciais e demais atividades" },
  { code: "05665", label: "físicas. Instrutor de ginástica, dança, esportes, natação, artes marciais e" },
  { code: "05673", label: "demais atividades físicas (profissional autônomo). Ensino regular pré-escolar, fundamental e médio, inclusive" },
  { code: "05681", label: "profissionalizantes. Professor de ensino regular pré-escolar, fundamental e médio" },
  { code: "05690", label: "inclusive cursos profissionalizantes (profissional autônomo). Ensino superior, cursos de graduação e demais" },
  { code: "05711", label: "Ensino superior, cursos de pós-graduação, mestrado, doutorado, pós-" },
  { code: "05720", label: "doutorado. Professor de ensino superior, inclusive cursos de graduação, pós- graduação, mestrado, doutorado" },
  { code: "05738", label: "seqüenciais (profissional autônomo). Auto-escolas, moto-escolas e congêneres" },
  { code: "05754", label: "Outros serviços de instrução, treinamento, orientação pedagógica e educacional, avaliação de conhecimentos de" },
  { code: "05762", label: "(profissional autônomo). Outros serviços de instrução, treinamento, orientação pedagógica e" },
  { code: "05771", label: "educacional, avaliação de conhecimentos de qualquer natureza. Administração de fundos quaisquer" },
  { code: "05800", label: "Organização e administração de consórcios" },
  { code: "05820", label: "Administração de cartão de crédito ou débito e congêneres, inclusive os serviços de credenciamento, de" },
  { code: "05836", label: "estabelecimentos e de captura e transmissão das transações. Administração de carteira de clientes" },
  { code: "05837", label: "Administração de cheques pré-datados e congêneres" },
  { code: "05851", label: "Arrendamento mercantil (\"leasing\") de quaisquer bens, inclusive cessão de direitos e obrigações, substituição" },
  { code: "05870", label: "exterior, bem como a manutenção das referidas contas ativas e inativas. Locação e manutenção de cofres" },
  { code: "05871", label: "de terminais de atendimento e de bens e equipamentos em geral. Fornecimento ou emissão de atestados em geral" },
  { code: "05872", label: "idoneidade, atestado de capacidade financeira e congêneres. Cadastro, elaboração de ficha cadastral" },
  { code: "05873", label: "Cheques sem Fundos - CCF ou em quaisquer outros bancos cadastrais. Emissão, reemissão e fornecimento de" },
  { code: "05874", label: "administração central; licenciamento eletrônico de veículos; transferência de veículos; agenciamento" },
  { code: "05875", label: "horas; acesso a outro banco e à rede compartilhada; fornecimento de saldo, extrato e demais informações" },
  { code: "05876", label: "de aval, fiança, anuência e congêneres; serviços relativos à abertura de crédito, para quaisquer fins" },
  { code: "05877", label: "máquinas de atendimento; fornecimento de posição de cobrança, recebimento ou pagamento; emissão de fichas de" },
  { code: "05878", label: "cancelamento e registro de contrato, e demais serviços relacionados ao arrendamento mercantil (\"leasing\")" },
  { code: "05879", label: "de atendimento; emissão de carnês, exceto os serviços relacionados a pagamentos, por meio eletrônico" },
  { code: "05881", label: "eles relacionados. alteração, prorrogação, cancelamento e baixa de contrato de câmbio; emissão de registro de" },
  { code: "05885", label: "viagem; fornecimento, transferência, cancelamento e demais serviços relativos à carta de crédito de" },
  { code: "05886", label: "de cheques quaisquer, avulso ou por talão. imóvel ou obra, análise técnica e jurídica, emissão, reemissão" },
  { code: "05887", label: "reemissão do termo de quitação e demais serviços relacionados a crédito imobiliário. Fornecimento, emissão" },
  { code: "05888", label: "congêneres. Custódia em geral, inclusive de títulos e valores mobiliários, realizada" },
  { code: "05889", label: "pela Bolsa de Valores, Mercadorias e Futuros - BM&FBOVESPA S.A. Custódia em geral, inclusive de títulos e" },
  { code: "05890", label: "Compensação de títulos quaisquer; serviços relacionados a depósito, inclusive depósito identificado, a saque" },
  { code: "05891", label: "atendimento, realizados pela Bolsa de Valores, Mercadorias e Futuros - BM&FBOVESPA S.A. Compensação de" },
  { code: "05892", label: "por qualquer meio ou processo, inclusive em terminais eletrônicos e de atendimento. Emissão, reemissão" },
  { code: "05893", label: "fundos, pagamentos e similares, inclusive entre contas em geral, realizados pela Bolsa de Valores" },
  { code: "05894", label: "ou processo; serviços relacionados à transferência de valores, dados, fundos, pagamentos e similares" },
  { code: "05895", label: "Serviço 05895" },
  { code: "05916", label: "por facilitadores de pagamento" },
  { code: "05991", label: "prevenção e gerência de riscos seguráveis e congêneres. Representante de qualquer natureza, inclusive" },
  { code: "06009", label: "autônomo). Representação de qualquer natureza, inclusive comercial" },
  { code: "06017", label: "Distribuidor de bens de terceiros (profissional autônomo)" },
  { code: "06041", label: "Distribuição de bens de terceiros" },
  { code: "06050", label: "Agenciamento, corretagem ou intermediação de planos de previdência" },
  { code: "06076", label: "privada. Agenciamento, corretagem ou intermediação de câmbio" },
  { code: "06084", label: "Agenciamento ou intermediação de seguros" },
  { code: "06092", label: "Agenciamento, corretagem ou intermediação de cartões de crédito" },
  { code: "06114", label: "Agenciamento, corretagem ou intermediação de planos de saúde" },
  { code: "06122", label: "Agente, corretor ou intermediário de câmbio, de seguros, de cartões de crédito, de planos de saúde e de" },
  { code: "06130", label: "corretor de seguros (profissional autônomo). Corretagem de seguros" },
  { code: "06149", label: "Corretor de seguros (profissional autônomo)" },
  { code: "06157", label: "Agenciamento, corretagem ou intermediação de títulos em geral" },
  { code: "06165", label: "valores mobiliários e contratos quaisquer. Agente, corretor ou intermediário de títulos em geral, valores" },
  { code: "06173", label: "mobiliários e contratos quaisquer (profissional autônomo). Agenciamento, corretagem ou intermediação de" },
  { code: "06181", label: "literária. Agente, corretor ou intermediário de direitos de propriedade industrial (inclusive marcas e" },
  { code: "06190", label: "autônomo). Agenciamento, corretagem ou intermediação de contratos de" },
  { code: "06220", label: "arrendamento mercantil (\"leasing\"). Agenciamento, corretagem ou intermediação de contratos de franquia" },
  { code: "06238", label: "(\"franchising\"). Agenciamento, corretagem ou intermediação de contratos de franquia" },
  { code: "06262", label: "faturização (\"factoring\"). Agente, corretor ou intermediário de contratos de arrendamento mercantil" },
  { code: "06270", label: "de contratos de arrendamento mercantil (\"leasing\") e de faturização (\"factoring\") (profissional autônomo). 6" },
  { code: "06297", label: "âmbito de Bolsas de Mercadorias e Futuros, por quaisquer meios. Agenciamento, corretagem ou intermediação de" },
  { code: "06298", label: "abrangidos em outros itens ou subitens, por quaisquer meios, não referenciado em outro código de serviço" },
  { code: "06319", label: "abrangidos em outros itens ou subitens, por quaisquer meios, não referenciado em outro código de serviço. 19" },
  { code: "06320", label: "abrangidos em outros itens ou subitens, por quaisquer meios, não referenciado em outro código de serviço" },
  { code: "06335", label: "outros itens ou subitens, por quaisquer meios, não referenciado em outro código de serviço (profissional" },
  { code: "06343", label: "Agente marítimo (profissional autônomo)" },
  { code: "06351", label: "Agenciamento de notícias" },
  { code: "06386", label: "Agente de notícias (profissional autônomo)" },
  { code: "06394", label: "Agenciamento de publicidade e propaganda, inclusive o agenciamento" },
  { code: "06432", label: "de veiculação por quaisquer meios. Agente de publicidade e propaganda, inclusive o de veiculação por" },
  { code: "06475", label: "quaisquer meios (profissional autônomo). 6 Recrutamento, agenciamento, seleção e colocação de mão-de-obra" },
  { code: "06491", label: "Fornecimento de mão-de-obra, mesmo em caráter temporário, inclusive de empregados ou trabalhadores, avulsos" },
  { code: "06513", label: "contratados pelo prestador de serviço. Fornecimento de mão-de-obra, mesmo em caráter temporário, inclusive de" },
  { code: "06521", label: "contratados pelo prestador de serviço (profissional autônomo). Franquia (\"franchising\")" },
  { code: "06530", label: "6522 17.07 Franquia (\"franchising\")" },
  { code: "06556", label: "Leiloeiro e congêneres (profissional autônomo)" },
  { code: "06557", label: "Leiloeiro e congêneres" },
  { code: "06564", label: "Cobranças e recebimentos por conta de terceiros, protestos de títulos, sustação de protestos, devolução de" },
  { code: "06572", label: "e outros serviços correlatos (exceto serviços de instituições financeiras). Funerais, inclusive fornecimento" },
  { code: "06599", label: "fornecimento de véu, essa e outros adornos; embalsamento, embelezamento, conservação ou restauração de" },
  { code: "06602", label: "Planos ou convênio funerários" },
  { code: "06610", label: "Manutenção e conservação de jazigos e cemitérios" },
  { code: "06637", label: "6613 25.05 Cessão de uso de espaços em cemitérios para sepultamento" },
  { code: "06645", label: "congêneres" },
  { code: "06777", label: "congêneres (profissional autônomo). 6 Prestação de serviço não referenciado em outro código do grupo" },
  { code: "06793", label: "óperas, concertos, recitais, festivais e congêneres. Fonografia ou gravação de sons, inclusive trucagem" },
  { code: "06807", label: "mixagem e congêneres. Fonografia ou gravação de sons, inclusive trucagem, dublagem" },
  { code: "06815", label: "televisão). Fotografia e cinematografia, inclusive revelação, ampliação, cópia" },
  { code: "06816", label: "Reprografia, microfilmagem e digitalização, prestados por notários" },
  { code: "06831", label: "oficiais de registro ou seus prepostos" },
  { code: "06840", label: "Colocador de molduras e congêneres (profissional autônomo)" },
  { code: "06858", label: "Encadernação, gravação e douração de livros, revistas e congêneres" },
  { code: "06890", label: "Encadernador, gravador e dourador de livros, revistas e congêneres" },
  { code: "06912", label: "(profissional autônomo). Artes gráficas, tipografia, diagramação, paginação e gravação" },
  { code: "06920", label: "Artes gráficas, tipografia, diagramação, paginação e gravação" },
  { code: "06939", label: "(profissional autônomo). Composição gráfica, fotocomposição, clicheria, zincografia, litografia" },
  { code: "06955", label: "fotolitografia, estereotipia, serigrafia e outras matrizes de impressão. Composição gráfica, fotocomposição" },
  { code: "06963", label: "(profissional autônomo). Composição gráfica, inclusive composição de impressos gráficos" },
  { code: "06971", label: "visual, banners, adesivos e congêneres" },
  { code: "07005", label: "24.01 profissional autônomo. 6 e 29 Fonografia ou gravação de sons, inclusive trucagem, dublagem" },
  { code: "07013", label: "Hospedagem em pensões, albergues, pousadas, hospedarias" },
  { code: "07056", label: "ocupação por temporada com fornecimento de serviços e congêneres. 3 Hospedagem em motéis" },
  { code: "07099", label: "Hospedagem em apart-service condominiais, flat, apart-hotéis, hotéis" },
  { code: "07100", label: "residência, residence-service, suite service e congêneres. 3 Hospedagem de qualquer natureza em hotéis" },
  { code: "07110", label: "ocupação por temporada com fornecimento de serviço (profissional autônomo). 6 e 19 Agente, organizador" },
  { code: "07129", label: "(profissional autônomo). Agenciamento, organização, promoção, intermediação e execução de programas de" },
  { code: "07137", label: "congêneres. Agenciamento e intermediação de programas de turismo, passeios" },
  { code: "07153", label: "Guia de turismo (profissional autônomo)" },
  { code: "07161", label: "No 1º dia da realização do evento ou no dia Planejamento, organização e administração de feiras, exposições" },
  { code: "07170", label: "congressos e congêneres. ocorrer primeiro. No 1º dia da realização do evento ou no dia Planejamento" },
  { code: "07196", label: "congressos e congêneres (profissional autônomo). ocorrer primeiro. Organização de festas e recepções; bufê" },
  { code: "07218", label: "alimentação e bebidas, que fica sujeito ao ICMS). Recreação e animação, inclusive em festas e eventos de" },
  { code: "07234", label: "natureza. Prestação de serviço não referenciado em outro código do grupo Turismo, Hospedagem, Eventos e" },
  { code: "07285", label: "profissional autônomo. Recreação e animação, inclusive em festas e eventos de qualquer natureza (profissional" },
  { code: "07315", label: "fornecido. Instalação e montagem industrial, prestada ao usuário final" },
  { code: "07323", label: "exclusivamente com material por ele fornecido" },
  { code: "07331", label: "Bens, prestado por profissional autônomo. 6 e 26 Lustração de bens móveis" },
  { code: "07366", label: "Lubrificação, lavagem e limpeza não automáticas de veículos, exceto" },
  { code: "07390", label: "em postos de gasolina. Lubrificação, lavagem e limpeza de veículos, inclusive automáticas, em" },
  { code: "07412", label: "postos de gasolina. Lubrificação, lavagem e limpeza automáticas de veículos, exceto em" },
  { code: "07439", label: "postos de gasolina. Lubrificação, limpeza, revisão de máquinas, aparelhos, equipamentos" },
  { code: "07447", label: "motores, elevadores e objetos de qualquer natureza, exceto veículos. Carga e recarga de aparelhos" },
  { code: "07455", label: "natureza. Conserto, restauração, manutenção, conservação e pintura de veículos, exceto os serviços executados" },
  { code: "07471", label: "revendedor autorizado (exceto peças e partes empregadas, que ficam sujeitas ao ICMS). Conserto, restauração" },
  { code: "07498", label: "peças e partes empregadas, que ficam sujeitas ao ICMS). Conserto, restauração, manutenção e conservação de" },
  { code: "07510", label: "objetos, exceto veículos (exceto peças e partes empregadas, que ficam sujeitas ao ICMS). Blindagem" },
  { code: "07528", label: "Sapateiro remendão (profissional autônomo)" },
  { code: "07536", label: "Afiador de utensílios domésticos e afinador de instrumentos musicais" },
  { code: "07552", label: "não estabelecidos (profissional autônomo). Retífica e recondicionamento de motores (exceto peças e partes" },
  { code: "07560", label: "empregadas, que ficam sujeitas ao ICMS). Recauchutagem ou regeneração de pneus, borracharia" },
  { code: "07579", label: "Restauração, recondicionamento, acondicionamento, pintura, beneficiamento, lavagem, secagem, tingimento" },
  { code: "07595", label: "anodização, corte, recorte, polimento, plastificação, costura, acabamento, e congêneres, de objetos" },
  { code: "07609", label: "usuário final, exceto aviamento. Alfaiataria, costura e congêneres, quando o material for fornecido pelo" },
  { code: "07617", label: "usuário final, exceto aviamento (profissional autônomo). Tinturaria e lavanderia" },
  { code: "07633", label: "Tintureiro individual" },
  { code: "07641", label: "Tapeçaria e reforma de estofamentos em geral" },
  { code: "07676", label: "Funilaria e lanternagem, incluindo a pintura" },
  { code: "07692", label: "Retífica e recondicionamento de motores (exceto peças e partes" },
  { code: "07765", label: "Cessão de direito de uso de marcas e de sinais de propaganda" },
  { code: "07773", label: "Exploração de salões de festas, escritórios virtuais, quadras esportivas, estádios, ginásios, auditórios" },
  { code: "07774", label: "diversões, canchas e congêneres, para realização de eventos ou negócios de qualquer natureza. Exploração de" },
  { code: "07790", label: "feiras, exposições, congressos e congêneres. Locação, sublocação, arrendamento, direito de passagem ou" },
  { code: "07803", label: "cabos, dutos e condutos de qualquer natureza. Cessão de andaimes, palcos, coberturas e outras estruturas de" },
  { code: "07811", label: "temporário. Guarda e estacionamento de veículos terrestres automotores" },
  { code: "07838", label: "Guarda e estacionamento de veículos terrestres automotores, em" },
  { code: "07846", label: "postos de gasolina. Guarda e estacionamento de veículos terrestres automotores, do tipo" },
  { code: "07854", label: "\"valet service\". Guarda e estacionamento de aeronaves e de embarcações" },
  { code: "07870", label: "Vigilância, segurança ou monitoramento de bens, pessoas e" },
  { code: "07889", label: "semoventes. Vigilância, segurança ou monitoramento de bens, pessoas e" },
  { code: "07897", label: "semoventes (profissional autônomo). 6 e 25 Escolta, inclusive de veículos e cargas" },
  { code: "07919", label: "Escolta, inclusive de veículos e cargas (profissional autônomo)" },
  { code: "07927", label: "Armazenamento, depósito, carga, descarga, arrumação e guarda de" },
  { code: "07930", label: "bens de qualquer espécie. em qualquer via ou local, de veículos, cargas, pessoas e semoventes em circulação" },
  { code: "07931", label: "empresas de Tecnologia da Informação Veicular, independentemente de o prestador de serviços ser proprietário" },
  { code: "07951", label: "empresas de Tecnologia da Informação Veicular, independentemente de o prestador de serviços ser proprietário" },
  { code: "07960", label: "movimentação de mercadorias, serviços de apoio marítimo, de movimentação ao largo, serviços de armadores" },
  { code: "07978", label: "congêneres. movimentação de passageiros, mercadorias, inclusive suas operações" },
  { code: "08036", label: "logística e congêneres" },
  { code: "08037", label: "exploração de “stands” e centros de convenções para a promoção de" },
  { code: "08044", label: "feiras, exposições, congressos e congêneres (profissional autônomo). 6 e 21" },
  { code: "08052", label: "Diversões Públicas, prestado por profissional autônomo" },
  { code: "08079", label: "8 Exibições cinematográficas" },
  { code: "08080", label: "Exibições cinematográficas (profissional autônomo)" },
  { code: "08087", label: "Espetáculos circenses" },
  { code: "08095", label: "Programas de auditório" },
  { code: "08117", label: "Parques de diversões, centros de lazer e congêneres" },
  { code: "08125", label: "Boates, taxi-dancing, night-club, cabaré, danceteria, casas noturnas, bares noturnos, restaurantes dançantes" },
  { code: "08133", label: "diversão pública com cobrança de couvert artístico e congêneres. Shows, bailes, desfiles, festivais e" },
  { code: "08168", label: "Óperas, ballet, danças, concertos, recitais e congêneres" },
  { code: "08176", label: "Feiras, exposições, congressos e congêneres" },
  { code: "08192", label: "Corridas e competições de animais" },
  { code: "08206", label: "Competições esportivas ou de destreza física ou intelectual, com ou" },
  { code: "08210", label: "sem a participação do espectador. Competições esportivas ou de destreza física ou intelectual, com ou" },
  { code: "08211", label: "sem a participação do espectador. Competições esportivas ou de destreza física ou intelectual, com ou" },
  { code: "08214", label: "sem a participação do espectador (profissional autônomo). Desfiles de blocos carnavalescos ou folclóricos" },
  { code: "08230", label: "prestado por contribuinte não estabelecido no Município de São Paulo. mediante regime especial Exibição de" },
  { code: "08257", label: "congêneres. Pago por antecipação ao pedido de Parques de diversões, centros de lazer e congêneres" },
  { code: "08272", label: "estabelecido no Município de São Paulo). mediante regime especial Competições esportivas ou de destreza" },
  { code: "08281", label: "Município de São Paulo). mediante regime especial" },
  { code: "08290", label: "prestado por contribuinte estabelecido no Município de São Paulo. Pago por antecipação ao pedido de" },
  { code: "08311", label: "intelectual ou congêneres. Bilhar por tempo (snooker), bilhar por ficha e pebolim" },
  { code: "08320", label: "Boliche" },
  { code: "08338", label: "Divertimento eletrônico, inclusive vitrola automática, cabines privê, computadores, videogames, videokê e" },
  { code: "08354", label: "acionados por fichas, cartões, ou quaisquer outros dispositivos. Divertimento eletrônico, inclusive vitrola" },
  { code: "08362", label: "centers e parques de diversões. Máquina Eletronicamente Programável ou outra máquina de" },
  { code: "08370", label: "entretenimento, com distribuição de prêmios. Máquina Eletronicamente Programável ou outra máquina de" },
  { code: "08397", label: "estabelecimentos do tipo bingo. Carteado, dominó, víspora, e outros tipos de diversões com cobrança" },
  { code: "08400", label: "facultativa de ingresso. Execução de música, individualmente ou por conjunto" },
  { code: "08419", label: "Fornecimento de música para ambientes fechados ou não, mediante" },
  { code: "08478", label: "transmissão por qualquer processo. Distribuição e venda de cartelas, sorteios ou prêmios em bingos" },
  { code: "08479", label: "inclusive os decorrentes de títulos de capitalização e congêneres. Distribuição e venda de cartelas, sorteios" },
  { code: "08480", label: "telebingos e assemelhados. Distribuição e venda de cartelas, sorteios ou prêmios em bingos" },
  { code: "08482", label: "telebingos e assemelhados (profissional autônomo). Serviços de apostas online" },
  { code: "08483", label: "Serviços de apostas online (profissional autônomo)" },
  { code: "08486", label: "telebingos e assemelhados. loteria, cartões, pules ou cupons de apostas, sorteios, prêmios" },
  { code: "08488", label: "8487 19.01 loteria, cartões, pules ou cupons de apostas, sorteios, prêmios" },
  { code: "08494", label: "inclusive os decorrentes de títulos de capitalização e congêneres (profissional autônomo). Barbearia" },
  { code: "08516", label: "Esteticistas, tratamento de pele, depilação e congêneres" },
  { code: "08532", label: "Banhos, duchas, sauna, massagens e congêneres" },
  { code: "08567", label: "Centros de emagrecimento, \"spa\" e congêneres" },
  { code: "08648", label: "6.01" },
  { code: "08656", label: "congêneres, relativos a animais. Guardador, tratador, amestrador, embelezador, alojador e congêneres" },
  { code: "08664", label: "relativos a animais (profissional autônomo). 6 Detetive particular (profissional autônomo)" },
  { code: "08672", label: "Serviços de investigações particulares, detetives e congêneres" },
  { code: "08770", label: "Artista circense e músico, não estabelecido (profissional autônomo)" },
  { code: "08842", label: "Serviços de artistas, atletas, modelos e manequins" },
  { code: "08850", label: "Artistas, atletas, modelos e manequins (profissional autônomo)" },
  { code: "08885", label: "Serviço 08885" },
  { code: "08893", label: "pelo tomador do serviço). Serviços relativos a obras de arte sob encomenda" },
];

export function findNfseServiceCode(code: string): NfseServiceCode | undefined {
  const digits = code.replace(/\D/g, "").padStart(5, "0");
  return NFSE_SERVICE_CODES.find((item) => item.code === digits);
}

