/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CadastroRouteImport } from './routes/cadastro'
import { Route as ClientesRouteImport } from './routes/clientes'
import { Route as ConfiguracoesRouteImport } from './routes/configuracoes'
import { Route as EmitirRouteImport } from './routes/emitir'
import { Route as EmitirNfseRouteImport } from './routes/emitir-nfse'
import { Route as LoginRouteImport } from './routes/login'
import { Route as NfseRouteImport } from './routes/nfse'
import { Route as NotasRouteImport } from './routes/notas'
import { Route as PainelRouteImport } from './routes/painel'
import { Route as ProdutosRouteImport } from './routes/produtos'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CadastroRoute = CadastroRouteImport.update({
  id: '/cadastro',
  path: '/cadastro',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientesRoute = ClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfiguracoesRoute = ConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => rootRouteImport,
} as any)
const EmitirRoute = EmitirRouteImport.update({
  id: '/emitir',
  path: '/emitir',
  getParentRoute: () => rootRouteImport,
} as any)
const EmitirNfseRoute = EmitirNfseRouteImport.update({
  id: '/emitir-nfse',
  path: '/emitir-nfse',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const NfseRoute = NfseRouteImport.update({
  id: '/nfse',
  path: '/nfse',
  getParentRoute: () => rootRouteImport,
} as any)
const NotasRoute = NotasRouteImport.update({
  id: '/notas',
  path: '/notas',
  getParentRoute: () => rootRouteImport,
} as any)
const PainelRoute = PainelRouteImport.update({
  id: '/painel',
  path: '/painel',
  getParentRoute: () => rootRouteImport,
} as any)
const ProdutosRoute = ProdutosRouteImport.update({
  id: '/produtos',
  path: '/produtos',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cadastro': typeof CadastroRoute
  '/clientes': typeof ClientesRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/emitir': typeof EmitirRoute
  '/emitir-nfse': typeof EmitirNfseRoute
  '/login': typeof LoginRoute
  '/nfse': typeof NfseRoute
  '/notas': typeof NotasRoute
  '/painel': typeof PainelRoute
  '/produtos': typeof ProdutosRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cadastro': typeof CadastroRoute
  '/clientes': typeof ClientesRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/emitir': typeof EmitirRoute
  '/emitir-nfse': typeof EmitirNfseRoute
  '/login': typeof LoginRoute
  '/nfse': typeof NfseRoute
  '/notas': typeof NotasRoute
  '/painel': typeof PainelRoute
  '/produtos': typeof ProdutosRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cadastro': typeof CadastroRoute
  '/clientes': typeof ClientesRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/emitir': typeof EmitirRoute
  '/emitir-nfse': typeof EmitirNfseRoute
  '/login': typeof LoginRoute
  '/nfse': typeof NfseRoute
  '/notas': typeof NotasRoute
  '/painel': typeof PainelRoute
  '/produtos': typeof ProdutosRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cadastro'
    | '/clientes'
    | '/configuracoes'
    | '/emitir'
    | '/emitir-nfse'
    | '/login'
    | '/nfse'
    | '/notas'
    | '/painel'
    | '/produtos'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cadastro'
    | '/clientes'
    | '/configuracoes'
    | '/emitir'
    | '/emitir-nfse'
    | '/login'
    | '/nfse'
    | '/notas'
    | '/painel'
    | '/produtos'
  id:
    | '__root__'
    | '/'
    | '/cadastro'
    | '/clientes'
    | '/configuracoes'
    | '/emitir'
    | '/emitir-nfse'
    | '/login'
    | '/nfse'
    | '/notas'
    | '/painel'
    | '/produtos'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CadastroRoute: typeof CadastroRoute
  ClientesRoute: typeof ClientesRoute
  ConfiguracoesRoute: typeof ConfiguracoesRoute
  EmitirRoute: typeof EmitirRoute
  EmitirNfseRoute: typeof EmitirNfseRoute
  LoginRoute: typeof LoginRoute
  NfseRoute: typeof NfseRoute
  NotasRoute: typeof NotasRoute
  PainelRoute: typeof PainelRoute
  ProdutosRoute: typeof ProdutosRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cadastro': {
      id: '/cadastro'
      path: '/cadastro'
      fullPath: '/cadastro'
      preLoaderRoute: typeof CadastroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clientes': {
      id: '/clientes'
      path: '/clientes'
      fullPath: '/clientes'
      preLoaderRoute: typeof ClientesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuracoes': {
      id: '/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof ConfiguracoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/emitir': {
      id: '/emitir'
      path: '/emitir'
      fullPath: '/emitir'
      preLoaderRoute: typeof EmitirRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/emitir-nfse': {
      id: '/emitir-nfse'
      path: '/emitir-nfse'
      fullPath: '/emitir-nfse'
      preLoaderRoute: typeof EmitirNfseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nfse': {
      id: '/nfse'
      path: '/nfse'
      fullPath: '/nfse'
      preLoaderRoute: typeof NfseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notas': {
      id: '/notas'
      path: '/notas'
      fullPath: '/notas'
      preLoaderRoute: typeof NotasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/painel': {
      id: '/painel'
      path: '/painel'
      fullPath: '/painel'
      preLoaderRoute: typeof PainelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produtos': {
      id: '/produtos'
      path: '/produtos'
      fullPath: '/produtos'
      preLoaderRoute: typeof ProdutosRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CadastroRoute: CadastroRoute,
  ClientesRoute: ClientesRoute,
  ConfiguracoesRoute: ConfiguracoesRoute,
  EmitirRoute: EmitirRoute,
  EmitirNfseRoute: EmitirNfseRoute,
  LoginRoute: LoginRoute,
  NfseRoute: NfseRoute,
  NotasRoute: NotasRoute,
  PainelRoute: PainelRoute,
  ProdutosRoute: ProdutosRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
